import json
import glob
import argparse
import matplotlib.pyplot as plt
from matplotlib.cm import get_cmap

def load_json_files(start_id, end_id):
    data = {}
    for i in range(start_id, end_id + 1):
        filename = f"node{i}.json"
        try:
            with open(filename, "r") as f:
                data[i] = json.load(f)
        except FileNotFoundError:
            pass
    return data

def visualize_data(data):
    fig, axs = plt.subplots(2, 1, figsize=(10, 20))
    cmap = get_cmap("tab10")

    for i, (node_id, node_data) in enumerate(data.items()):
        color = cmap(i % 10)
        
        # Plot paths
        for path_vehicle in node_data["multipath"]:
            path = path_vehicle["path"]
            xs, ys = zip(*[(p["x"], p["y"]) for p in path])
            axs[0].plot(xs, ys, color=color)
        
        # Plot avoid conflicts
        for avoid in node_data["avoid"]:
            axs[0].scatter(avoid["x"], avoid["y"], color=color, marker="x")

        # Plot interprimitive positions
        for path_vehicle in node_data["multipath"]:
            interprimitive = path_vehicle["interprimitive"]
            xs, ys = zip(*[(p["x"], p["y"]) for p in interprimitive])
            sc = axs[1].scatter(xs, ys, color=color)

            # Add file IDs to the trajectories in the second plot
            axs[1].text(xs[-1], ys[-1], f"{node_id}", fontsize=9, color=color)

            # Plot obstacles as transparent circles in the second plot
            for avoid in node_data["avoid"]:
                obstacle = plt.Circle((avoid["x"], avoid["y"]), radius=20, color=color, alpha=0.2)
                axs[1].add_artist(obstacle)

        # Highlight path differences
        if i > 0:
            prev_node_id, prev_node_data = list(data.items())[i - 1]
            if prev_node_id + 1 == node_id:
                for prev_path_vehicle, path_vehicle in zip(prev_node_data["multipath"], node_data["multipath"]):
                    prev_path = prev_path_vehicle["path"]
                    path = path_vehicle["path"]
                    if prev_path != path:
                        axs[1].scatter(*zip(*[[p["x"], p["y"]] for p in path]), color="red", marker="x")

        axs[0].legend([f"Node {node_id}" for node_id in data.keys()], title="Node IDs")

    axs[0].set_title("Paths and Avoid Conflicts")
    axs[0].set_xlabel("X Position")
    axs[0].set_ylabel("Y Position")

    axs[1].set_title("Interprimitive Positions with Path Differences Highlighted")
    axs[1].set_xlabel("X Position")
    axs[1].set_ylabel("Y Position")

    plt.tight_layout()
    plt.savefig("../conflicts_over_time.png")

def main():
    parser = argparse.ArgumentParser(description="Visualize JSON data generated by CBSPlanner.")
    parser.add_argument("start_id", type=int, help="Starting node ID.")
    parser.add_argument("end_id", type=int, help="Ending node ID.")
    args = parser.parse_args()

    data = load_json_files(args.start_id, args.end_id)
    visualize_data(data)

if __name__ == "__main__":
    main()
